mkdir -p "$XDG_CACHE_HOME/zsh" "$XDG_STATE_HOME/zsh"

for module in \
  options \
  completion \
  aliases \
  integrations \
  plugins; do
  source "$ZDOTDIR/$module.zsh"
done
unset module

[[ -r "$ZDOTDIR/local.zsh" ]] && source "$ZDOTDIR/local.zsh"
