[General]
DisplayServer=wayland

[Theme]
Current=vesper
FacesDir=/usr/share/sddm/faces

[Users]
MaximumUid=60000
MinimumUid=1000

[Wayland]
CompositorCommand=weston --shell=kiosk
EnableHiDPI=true
SessionCommand=/usr/share/sddm/scripts/wayland-session
